from .I2Caption import NODE_CLASS_MAPPINGS as CAPTION_MAPPINGS
from .I2Caption import NODE_DISPLAY_NAME_MAPPINGS as CAPTION_DISPLAY_MAPPINGS
from .I2Caption_resolution import NODE_CLASS_MAPPINGS as RES_MAPPINGS
from .I2Caption_resolution import NODE_DISPLAY_NAME_MAPPINGS as RES_DISPLAY_MAPPINGS
from .I2Caption_latent import NODE_CLASS_MAPPINGS as LATENT_MAPPINGS
from .I2Caption_latent import NODE_DISPLAY_NAME_MAPPINGS as LATENT_DISPLAY_MAPPINGS
from .I2Caption_loader import NODE_CLASS_MAPPINGS as LOADER_MAPPINGS
from .I2Caption_loader import NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY_MAPPINGS
import os

NODE_CLASS_MAPPINGS = {**CAPTION_MAPPINGS, **RES_MAPPINGS, **LATENT_MAPPINGS, **LOADER_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**CAPTION_DISPLAY_MAPPINGS, **RES_DISPLAY_MAPPINGS, **LATENT_DISPLAY_MAPPINGS, **LOADER_DISPLAY_MAPPINGS}

WEB_DIRECTORY = os.path.join(os.path.dirname(__file__), "web")

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
